export const SLCContractAddress = '0x4f54acbE20F61Ab83B7235b1EdC1E0DfcFB98967'
export const SLFContractAddress = '0xfC105f097Be85EC698D11e9ab2B9744F2A991749'

export const selfAbi: any = [
  { inputs: [], stateMutability: 'nonpayable', type: 'constructor' },
  {
    anonymous: false,
    inputs: [{ indexed: false, internalType: 'address', name: '', type: 'address' }],
    name: 'AdminDeleted',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, internalType: 'address', name: '', type: 'address' }],
    name: 'NewAdminAdded',
    type: 'event',
  },
  {
    inputs: [{ internalType: 'address', name: '', type: 'address' }],
    name: 'AdminMApping',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: '_origValue', type: 'uint256' },
      { internalType: 'uint256', name: '_currValue', type: 'uint256' },
      { internalType: 'uint256', name: '_coins_issued', type: 'uint256' },
      { internalType: 'uint256', name: '_equity_at_issuance', type: 'uint256' },
      { internalType: 'uint256', name: '_varriation', type: 'uint256' },
      { internalType: 'uint256', name: '_current_coin_value', type: 'uint256' },
      { internalType: 'uint256', name: '_orig_issue_rate', type: 'uint256' },
      { internalType: 'uint256', name: '_next_schedule_reevaluation', type: 'uint256' },
      { internalType: 'string', name: 'token_uri', type: 'string' },
      { internalType: 'string', name: 'propertyID', type: 'string' },
    ],
    name: 'ListProperty_details',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'newAdmin', type: 'address' }],
    name: 'addAdmin',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'ExistingAdmin', type: 'address' }],
    name: 'delAdmin',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'property_id', type: 'uint256' }],
    name: 'listFromTempInfo',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    name: 'propInfo',
    outputs: [
      { internalType: 'uint256', name: 'origValue', type: 'uint256' },
      { internalType: 'uint256', name: 'currValue', type: 'uint256' },
      { internalType: 'uint256', name: 'coins_issued', type: 'uint256' },
      { internalType: 'uint256', name: 'equity_at_issuance', type: 'uint256' },
      { internalType: 'uint256', name: 'Total_Current_Value', type: 'uint256' },
      { internalType: 'uint256', name: 'Varriation', type: 'uint256' },
      { internalType: 'uint256', name: 'Current_Coin_Value', type: 'uint256' },
      { internalType: 'uint256', name: 'Original_Issuance_Rate', type: 'uint256' },
      { internalType: 'uint256', name: 'Next_Schedule_Revaluation', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '_address', type: 'address' }],
    name: 'setSLC_contract_address',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    name: 'temppropInfo',
    outputs: [
      { internalType: 'uint256', name: 'origValue', type: 'uint256' },
      { internalType: 'uint256', name: 'currValue', type: 'uint256' },
      { internalType: 'uint256', name: 'coins_issued', type: 'uint256' },
      { internalType: 'uint256', name: 'equity_at_issuance', type: 'uint256' },
      { internalType: 'uint256', name: 'Total_Current_Value', type: 'uint256' },
      { internalType: 'uint256', name: 'Varriation', type: 'uint256' },
      { internalType: 'uint256', name: 'Current_Coin_Value', type: 'uint256' },
      { internalType: 'uint256', name: 'Original_Issuance_Rate', type: 'uint256' },
      { internalType: 'uint256', name: 'Next_Schedule_Revaluation', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
]
export const slcAbi: any = [
  { inputs: [{ internalType: 'uint256', name: '_initialSupply', type: 'uint256' }], stateMutability: 'nonpayable', type: 'constructor' },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: '_owner', type: 'address' },
      { indexed: true, internalType: 'address', name: '_spender', type: 'address' },
      { indexed: false, internalType: 'uint256', name: '_value', type: 'uint256' },
    ],
    name: 'Approval',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: 'address', name: '', type: 'address' },
      { indexed: false, internalType: 'uint256', name: '', type: 'uint256' },
    ],
    name: 'DepositFunds',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: 'uint256', name: '', type: 'uint256' },
      { indexed: false, internalType: 'address', name: '', type: 'address' },
    ],
    name: 'RegionAdminAdded',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: 'uint256', name: '', type: 'uint256' },
      { indexed: false, internalType: 'address', name: '', type: 'address' },
    ],
    name: 'RegionAdminChanged',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: 'address', name: '', type: 'address' },
      { indexed: false, internalType: 'uint256', name: '', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: '', type: 'uint256' },
      { indexed: false, internalType: 'string', name: '', type: 'string' },
    ],
    name: 'TransactionCompleted',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: 'address', name: '', type: 'address' },
      { indexed: false, internalType: 'uint256', name: '', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: '', type: 'uint256' },
      { indexed: false, internalType: 'string', name: '', type: 'string' },
    ],
    name: 'TransactionCreated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: 'address', name: '', type: 'address' },
      { indexed: false, internalType: 'uint256', name: '', type: 'uint256' },
    ],
    name: 'TransactionSigned',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: '_from', type: 'address' },
      { indexed: true, internalType: 'address', name: '_to', type: 'address' },
      { indexed: false, internalType: 'uint256', name: '_value', type: 'uint256' },
    ],
    name: 'Transfer',
    type: 'event',
  },
  { anonymous: false, inputs: [{ indexed: false, internalType: 'address', name: '', type: 'address' }], name: 'ownerAdded', type: 'event' },
  {
    anonymous: false,
    inputs: [{ indexed: false, internalType: 'address', name: '', type: 'address' }],
    name: 'ownerRemoved',
    type: 'event',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'tokenid', type: 'uint256' },
      { internalType: 'address', name: 'receiver', type: 'address' },
      { internalType: 'uint256', name: 'amount', type: 'uint256' },
      { internalType: 'string', name: 'token_uri', type: 'string' },
      { internalType: 'string', name: 'propertyID', type: 'string' },
    ],
    name: 'InitiateTransaction',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'SLf_contract_address',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '', type: 'address' }],
    name: '_owners',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    name: '_pendingTransactions',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: '_transactionIdx',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    name: '_transactions',
    outputs: [
      { internalType: 'address', name: 'to', type: 'address' },
      { internalType: 'uint256', name: 'amount', type: 'uint256' },
      { internalType: 'uint256', name: 'tokenid', type: 'uint256' },
      { internalType: 'uint8', name: 'signatureCount', type: 'uint8' },
      { internalType: 'string', name: 'tokenURI', type: 'string' },
      { internalType: 'string', name: 'propertyID', type: 'string' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '_owner', type: 'address' }],
    name: 'addOwner',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'region_no', type: 'uint256' },
      { internalType: 'address', name: '_address', type: 'address' },
    ],
    name: 'add_region_admin',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '', type: 'address' },
      { internalType: 'address', name: '', type: 'address' },
    ],
    name: 'allowance',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_spender', type: 'address' },
      { internalType: 'uint256', name: '_value', type: 'uint256' },
    ],
    name: 'approve',
    outputs: [{ internalType: 'bool', name: 'success', type: 'bool' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'request', type: 'address' }],
    name: 'balanceOf',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: '_region_no', type: 'uint256' },
      { internalType: 'address', name: '_address', type: 'address' },
    ],
    name: 'change_region_admin',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'decimals',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'transactionId', type: 'uint256' }],
    name: 'deleteTransaction',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getPendingTransactions',
    outputs: [{ internalType: 'uint256[]', name: '', type: 'uint256[]' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'mintNFT_contract_address',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_oldAddress', type: 'address' },
      { internalType: 'address', name: '_newAddress', type: 'address' },
    ],
    name: 'modify',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  { inputs: [], name: 'name', outputs: [{ internalType: 'string', name: '', type: 'string' }], stateMutability: 'view', type: 'function' },
  {
    inputs: [],
    name: 'owner',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '_owner', type: 'address' }],
    name: 'removeOwner',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_from', type: 'address' },
      { internalType: 'address', name: '_to', type: 'address' },
      { internalType: 'uint256', name: '_value', type: 'uint256' },
    ],
    name: 'safetransferFrom',
    outputs: [{ internalType: 'bool', name: 'success', type: 'bool' }],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '_address', type: 'address' }],
    name: 'setSLF_contract_address',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '_address', type: 'address' }],
    name: 'setmintNFT_contract_address',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'transactionId', type: 'uint256' }],
    name: 'signTransaction',
    outputs: [],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'symbol',
    outputs: [{ internalType: 'string', name: '', type: 'string' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'totalSupply',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'walletBalance',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  { stateMutability: 'payable', type: 'receive' },
]
