export enum Paths {
  root = '/',
  // root = '/portfolio',
  dashboard = '/dashboard',
  addPropertyForm = '/add-property-form',
  propertyDetails = '/property-details',
  ownerPropertyDetails = '/owner-property-details',
  editPropertyForm = '/edit-property-form',
  viewPropertyForm = '/view-property-form',
  treasuryPropertyDetails = '/treasury-property-details',
  auction = '/auction',
  auctionDetails = '/auction-details',
  upgradeBid = '/auction-upgrade-bid',
  portfolio = '/portfolio',
  login = '/login',
  learnMore = '/learnMore',
  icoDetails = '/icoDetails',
}
